plugins {
    id 'net.fabricmc.fabric-loom'
}

base {
    archivesName = "Skinnable-${mod_version}-fabric-mc${minecraft_version}"
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    compileOnly "net.fabricmc:fabric-loader:${fabric_loader_version}"
    compileOnly "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    compileOnly project(':common')
}

jar {
    from project(':common').sourceSets.main.output
    archiveVersion = ''
}

sourcesJar {
    archiveVersion = ''
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}
