plugins {
    id 'java'
}

allprojects {
    version = mod_version
    group = 'com.skinnable'

    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.neoforged.net/releases' }
        mavenCentral()
    }
}

subprojects {
    plugins.withId('java') {
        java {
            toolchain { languageVersion = JavaLanguageVersion.of(java_version as int) }
            withSourcesJar()
        }
    }
}
