org.gradle.jvmargs=-Xmx2G
org.gradle.java.installations.paths=C:\\Users\\family\\AppData\\Roaming\\.openJDK\\jdk-25.0.2

minecraft_version=26.1.2
java_version=25
neoforge_version=26.1.2.75
fabric_loader_version=0.19.3
fabric_api_version=0.150.0+26.1.2
loom_version=1.16-SNAPSHOT
moddevgradle_version=2.0.140

mod_version=1.1.0
group=com.skinnable
