modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="skinnable"
version="${file.jarVersion}"
displayName="Skinnable"
description='''
Disguise command blocks and mob spawners as any vanilla block.
'''
[[dependencies.skinnable]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.75,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.skinnable]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2,)"
    ordering="NONE"
    side="BOTH"
