plugins {
    id 'net.neoforged.moddev'
}

neoForge {
    version = "${neoforge_version}"

    runs {
        client {
            client()
            gameDirectory = project.file('runs/client')
        }
        server {
            server()
            gameDirectory = project.file('runs/server')
        }
    }

    mods {
        skinnable {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    compileOnly project(':common')
}

jar {
    from project(':common').sourceSets.main.output
}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}
